server:
   port: 8083
   
spring:
  cloud:
    stream:
      bindings:
        userInfoChangedChannel:
          destination: userInfoChangedTopic
          content-type: application/json          
          group: interventionGroup          
      kafka:
        binder:
          zk-nodes: localhost
          brokers: localhost
     
    config:
     enabled: true
     uri: http://localhost:8888

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
    level:
      com.netflix: WARN
      org.springframework.web: WARN
      com.tianyalan: INFO
